In [31]:
import tensorflow as tf
print(tf.__version__)

2.16.2


In [32]:
# Creating tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [33]:
# Dimention of a tensor
scalar.ndim

0

In [34]:
# create a vector
vector = tf.constant([10,7])

In [35]:
vector.ndim

1

In [36]:
# create a tensor 
matrix = tf.constant([[10,7],
                      [7,10]])

In [37]:
matrix.ndim

2

In [38]:
tensor = tf.constant([[[10,7],
                       [10,7],
                       [10,7]]])

In [39]:
tensor.ndim

3

In [40]:
changable_tensor = tf.Variable([10,7])

In [41]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [42]:
unchangable_tensor = tf.constant([10,7])

In [43]:
unchangable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [44]:
changable_tensor[0]= 7
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [45]:
changable_tensor[0].assign(000)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 7])>

In [46]:
unchangable_tensor[0].assign(900)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [47]:
# creating random tensors
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(2,3))
print(random1)
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(2,3))
print(random2)

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]], shape=(2, 3), dtype=float32)


In [48]:
random1 == random2

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

In [49]:
random2.ndim

2

In [51]:
# Shuffle a tensor 
not_shuffle = tf.constant([[10,7],
                          [2,5],
                           [6,7]])
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 6,  7]])>

In [52]:
tf.random.set_seed(42) # global level seed 
tf.random.shuffle(not_shuffle, seed=42)  # operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 6,  7]])>

In [53]:
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [54]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [55]:
import numpy as np
numpy_array = np.arange(1,25, dtype=np.int32)
print(numpy_array)
print(type(numpy_array))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
<class 'numpy.ndarray'>


In [56]:
numpy_to_tensor = tf.constant(numpy_array, shape =(2,3,4)) ## here the shape has to be same as the number of elements in the original array 
print(f"converted using method 2",numpy_to_tensor)
# print(numpy_array)
numpy_to_tensor2 = tf.convert_to_tensor(numpy_array)
print(f"converted using method1",numpy_to_tensor2)
print("oringinal numpy", numpy_array,type(numpy_array))

converted using method 2 tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
converted using method1 tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
oringinal numpy [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] <class 'numpy.ndarray'>


In [57]:
## Getting more information from tensors


In [58]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])

In [59]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [60]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [61]:
rank_4_tensor.ndim # rank or dimention of a tensor

4

In [62]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [63]:
# elements along the 0 axis 
rank_4_tensor.shape[0]

2

In [64]:
rank_4_tensor.shape[-1]

5

In [65]:
rank_4_tensor[:2,:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [66]:
rank_2_tensor = tf.constant([[10,7],
                            [5,9]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  9]])>

In [67]:
rank_3_dimention = rank_2_tensor[..., tf.newaxis]

In [68]:
rank_3_dimention

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 9]]])>

In [69]:
# Manipulating tensors this can be addition, subtraction multiplication as well
# 1 adding values to tensors
tensor = tf.constant([[10,7],
                      [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [70]:
tensor + 10 # This dont change the original tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [71]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [72]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [73]:
tf.math

<module 'tensorflow._api.v2.math' from 'd:\\TensorFlow\\.venv\\Lib\\site-packages\\tensorflow\\_api\\v2\\math\\__init__.py'>

In [74]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[5,6], [7, 8]])
result = tf.matmul(matrix1, matrix2)

In [75]:
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [76]:
b = tf.constant([1.2])
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>

In [77]:
c = tf.constant([5])
c.dtype

tf.int32

In [78]:
d = tf.cast(b, dtype=tf.float16)
d

<tf.Tensor: shape=(1,), dtype=float16, numpy=array([1.2], dtype=float16)>

In [79]:
tf.random.set_seed(42)
import numpy as np
E = tf.constant(np.random.randint(0, 100, size= 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([56, 59, 38, 29, 55, 75, 49, 13, 94, 14, 23, 84, 58, 44, 23, 60, 14,
       54,  6, 39, 61,  2, 23,  8, 23, 98, 95, 14, 29, 88, 93, 19, 59, 29,
       51, 13, 14, 75, 16, 55, 73, 90, 19, 45, 97,  4, 38, 13,  8, 99])>

In [80]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [81]:
varaince = tf.nn.moments(E, axes=[0])
print(varaince)

(<tf.Tensor: shape=(), dtype=int32, numpy=44>, <tf.Tensor: shape=(), dtype=int32, numpy=897>)


In [82]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=897>

In [83]:
tf.math.reduce_std(tf.cast(E, dtype =tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.94766>

In [84]:
# creating a new tensor for finding a positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [85]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [86]:
# index on largest value position 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [87]:
# Squeezing the tensors
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [88]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [89]:
G_squeezed = tf.squeeze(G)

In [90]:
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [91]:
G_squeezed.shape

TensorShape([50])

In [92]:
import tensorflow as tf

# Create a tensor with a dimension of size 1
data = tf.constant([[1, 2, 3], [4, 5, 6]])
original_shape = data  # Output: (2, 3, 1)

# Squeeze the tensor
squeezed_tensor = tf.squeeze(data)
squeezed_shape = squeezed_tensor.shape  # Output: (2, 3)

print("Original shape:", original_shape)
print("Squeezed shape:", squeezed_shape)


Original shape: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Squeezed shape: (2, 3)


In [93]:
# One hot encode 
some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth= 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [94]:
# specify custom values for one hot encoding 
tf.one_hot(some_list, depth=5, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

In [95]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [96]:
squared_data = tf.square(H)
squared_data

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [97]:
log_data =tf.math.log(tf.cast(H, dtype=tf.float32))
log_data


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [98]:
# tensors and numpy 
J = tf.constant(np.array([3.,4., 6,]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 6.])>